### ISSUE TITLE
Sign up and login are not working correctly

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-spring-mvc-sample#12] opened 2017-05-17 05:20 UTC
The result of try to sign up or login (using username and password) is:
![image](https://cloud.githubusercontent.com/assets/26749061/26139441/b4a3be7c-3a9e-11e7-8cd4-bb1f79a4b80b.png)

Also, the result to try to sign up or login using social providers is:
![image](https://cloud.githubusercontent.com/assets/26749061/26139480/e9f23716-3a9e-11e7-8990-e1b23c9e439c.png)

**Comment by jimmyjames** [comment] 2019-05-10 02:07
Hi @HeikerAraujo, as this issue is nearly two years old, and I've not been able to reproduce (there's been lots of changes to this sample and supporting SDKs since reporting), I'm going to close this issue. If you continue to have issues, don't hesitate to reopen this issue or create a new one (just be sure to include updated details about the issue). Thanks!

**Closed as completed by jimmyjames** 2019-05-10 02:07 UTC
